# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dist.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dist.proto',
  package='walle.dist',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ndist.proto\x12\nwalle.dist\"\x15\n\x08RspState\x12\t\n\x01s\x18\x01 \x01(\x05\"+\n\x07\x45nvInfo\x12\x0f\n\x07obs_dim\x18\x01 \x03(\x05\x12\x0f\n\x07\x61\x63t_dim\x18\x02 \x03(\x05\"\x13\n\x04Uids\x12\x0b\n\x03ids\x18\x01 \x03(\x05\"\x15\n\x06\x45nvCfg\x12\x0b\n\x03\x63\x66g\x18\x01 \x01(\t\":\n\x07\x41\x63tions\x12\x1e\n\x04uids\x18\x01 \x01(\x0b\x32\x10.walle.dist.Uids\x12\x0f\n\x07\x61\x63tions\x18\x02 \x01(\x0c\"\x1a\n\x0bObservation\x12\x0b\n\x03obs\x18\x01 \x01(\x0c\"P\n\x07Records\x12\x0b\n\x03obs\x18\x01 \x01(\x0c\x12\t\n\x01r\x18\x02 \x01(\x0c\x12\t\n\x01\x64\x18\x03 \x01(\x0c\x12\x12\n\x08\x65nv_info\x18\x04 \x01(\x0cH\x00\x42\x0e\n\x0coptional_env\"\x06\n\x04Void2\x96\x02\n\x05WALLE\x12\x34\n\x07\x43onnect\x12\x12.walle.dist.EnvCfg\x1a\x13.walle.dist.EnvInfo\"\x00\x12\x34\n\x05Reset\x12\x10.walle.dist.Uids\x1a\x17.walle.dist.Observation\"\x00\x12\x32\n\x04Step\x12\x13.walle.dist.Actions\x1a\x13.walle.dist.Records\"\x00\x12\x35\n\x06GetObs\x12\x10.walle.dist.Uids\x1a\x17.walle.dist.Observation\"\x00\x12\x36\n\nDisConnect\x12\x10.walle.dist.Void\x1a\x14.walle.dist.RspState\"\x00\x62\x06proto3')
)




_RSPSTATE = _descriptor.Descriptor(
  name='RspState',
  full_name='walle.dist.RspState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='s', full_name='walle.dist.RspState.s', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=47,
)


_ENVINFO = _descriptor.Descriptor(
  name='EnvInfo',
  full_name='walle.dist.EnvInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='obs_dim', full_name='walle.dist.EnvInfo.obs_dim', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='act_dim', full_name='walle.dist.EnvInfo.act_dim', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=92,
)


_UIDS = _descriptor.Descriptor(
  name='Uids',
  full_name='walle.dist.Uids',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='walle.dist.Uids.ids', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=113,
)


_ENVCFG = _descriptor.Descriptor(
  name='EnvCfg',
  full_name='walle.dist.EnvCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg', full_name='walle.dist.EnvCfg.cfg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=136,
)


_ACTIONS = _descriptor.Descriptor(
  name='Actions',
  full_name='walle.dist.Actions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uids', full_name='walle.dist.Actions.uids', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actions', full_name='walle.dist.Actions.actions', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=196,
)


_OBSERVATION = _descriptor.Descriptor(
  name='Observation',
  full_name='walle.dist.Observation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='obs', full_name='walle.dist.Observation.obs', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=224,
)


_RECORDS = _descriptor.Descriptor(
  name='Records',
  full_name='walle.dist.Records',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='obs', full_name='walle.dist.Records.obs', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='r', full_name='walle.dist.Records.r', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='d', full_name='walle.dist.Records.d', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='env_info', full_name='walle.dist.Records.env_info', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='optional_env', full_name='walle.dist.Records.optional_env',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=226,
  serialized_end=306,
)


_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='walle.dist.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=314,
)

_ACTIONS.fields_by_name['uids'].message_type = _UIDS
_RECORDS.oneofs_by_name['optional_env'].fields.append(
  _RECORDS.fields_by_name['env_info'])
_RECORDS.fields_by_name['env_info'].containing_oneof = _RECORDS.oneofs_by_name['optional_env']
DESCRIPTOR.message_types_by_name['RspState'] = _RSPSTATE
DESCRIPTOR.message_types_by_name['EnvInfo'] = _ENVINFO
DESCRIPTOR.message_types_by_name['Uids'] = _UIDS
DESCRIPTOR.message_types_by_name['EnvCfg'] = _ENVCFG
DESCRIPTOR.message_types_by_name['Actions'] = _ACTIONS
DESCRIPTOR.message_types_by_name['Observation'] = _OBSERVATION
DESCRIPTOR.message_types_by_name['Records'] = _RECORDS
DESCRIPTOR.message_types_by_name['Void'] = _VOID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspState = _reflection.GeneratedProtocolMessageType('RspState', (_message.Message,), dict(
  DESCRIPTOR = _RSPSTATE,
  __module__ = 'dist_pb2'
  # @@protoc_insertion_point(class_scope:walle.dist.RspState)
  ))
_sym_db.RegisterMessage(RspState)

EnvInfo = _reflection.GeneratedProtocolMessageType('EnvInfo', (_message.Message,), dict(
  DESCRIPTOR = _ENVINFO,
  __module__ = 'dist_pb2'
  # @@protoc_insertion_point(class_scope:walle.dist.EnvInfo)
  ))
_sym_db.RegisterMessage(EnvInfo)

Uids = _reflection.GeneratedProtocolMessageType('Uids', (_message.Message,), dict(
  DESCRIPTOR = _UIDS,
  __module__ = 'dist_pb2'
  # @@protoc_insertion_point(class_scope:walle.dist.Uids)
  ))
_sym_db.RegisterMessage(Uids)

EnvCfg = _reflection.GeneratedProtocolMessageType('EnvCfg', (_message.Message,), dict(
  DESCRIPTOR = _ENVCFG,
  __module__ = 'dist_pb2'
  # @@protoc_insertion_point(class_scope:walle.dist.EnvCfg)
  ))
_sym_db.RegisterMessage(EnvCfg)

Actions = _reflection.GeneratedProtocolMessageType('Actions', (_message.Message,), dict(
  DESCRIPTOR = _ACTIONS,
  __module__ = 'dist_pb2'
  # @@protoc_insertion_point(class_scope:walle.dist.Actions)
  ))
_sym_db.RegisterMessage(Actions)

Observation = _reflection.GeneratedProtocolMessageType('Observation', (_message.Message,), dict(
  DESCRIPTOR = _OBSERVATION,
  __module__ = 'dist_pb2'
  # @@protoc_insertion_point(class_scope:walle.dist.Observation)
  ))
_sym_db.RegisterMessage(Observation)

Records = _reflection.GeneratedProtocolMessageType('Records', (_message.Message,), dict(
  DESCRIPTOR = _RECORDS,
  __module__ = 'dist_pb2'
  # @@protoc_insertion_point(class_scope:walle.dist.Records)
  ))
_sym_db.RegisterMessage(Records)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
  DESCRIPTOR = _VOID,
  __module__ = 'dist_pb2'
  # @@protoc_insertion_point(class_scope:walle.dist.Void)
  ))
_sym_db.RegisterMessage(Void)



_WALLE = _descriptor.ServiceDescriptor(
  name='WALLE',
  full_name='walle.dist.WALLE',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=317,
  serialized_end=595,
  methods=[
  _descriptor.MethodDescriptor(
    name='Connect',
    full_name='walle.dist.WALLE.Connect',
    index=0,
    containing_service=None,
    input_type=_ENVCFG,
    output_type=_ENVINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Reset',
    full_name='walle.dist.WALLE.Reset',
    index=1,
    containing_service=None,
    input_type=_UIDS,
    output_type=_OBSERVATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Step',
    full_name='walle.dist.WALLE.Step',
    index=2,
    containing_service=None,
    input_type=_ACTIONS,
    output_type=_RECORDS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetObs',
    full_name='walle.dist.WALLE.GetObs',
    index=3,
    containing_service=None,
    input_type=_UIDS,
    output_type=_OBSERVATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DisConnect',
    full_name='walle.dist.WALLE.DisConnect',
    index=4,
    containing_service=None,
    input_type=_VOID,
    output_type=_RSPSTATE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WALLE)

DESCRIPTOR.services_by_name['WALLE'] = _WALLE

# @@protoc_insertion_point(module_scope)
